feature:
  - head-branch: ['feature/*', 'enhancement/*']

bug:
  - head-branch: ['fix/*', 'bugfix/*', 'bug/*']

documentation:
  - head-branch: ['docs/*', 'readme/*']

performance:
  - head-branch: ['perf/*', 'optimize/*']

dependencies:
  - head-branch: ['deps/*', 'upgrade/*']

# Infrastructure-specific labels
infra/terragrunt:
  - head-branch: ['infra/terragrunt/*']

infra/terraform:
  - head-branch: ['infra/terraform/*']

# Maintenance and configuration
maintenance:
  - head-branch: ['chore/*', 'config/*']

ci:
  - head-branch: ['ci/*', 'workflow/*']

# Breaking changes
breaking:
  - head-branch: ['breaking/*', 'major/*']

# Release preparation
release:
  - head-branch: ['release/*', 'prep/*']

# Test-related changes
tests:
  - head-branch: ['test/*', 'testing/*']

# Configuration-specific labels
config/root:
  - head-branch: ['config/root/*']

config/shared:
  - head-branch: ['config/shared/*']

config/environment:
  - head-branch: ['config/env/*']
