# Feature changes
feature:
- head-branch: ['^feature', 'feature']

# Bug fixes
bug:
- head-branch: ['^fix', '^bugfix', '^bug']

# Documentation changes
documentation:
- changed-files:
  - any-glob-to-any-file: ['**/*.md', 'docs/**/*']

# Infrastructure changes
infra/terragrunt:
- changed-files:
  - any-glob-to-any-file: 'infra/terragrunt/**/*.hcl'

infra/terraform:
- changed-files:
  - any-glob-to-any-file: 'infra/terraform/**/*.tf'

# CI changes
ci:
- changed-files:
  - any-glob-to-any-file: '.github/**/*'

# Breaking changes
breaking:
- head-branch: ['^breaking', '^major']

# Release preparation
release:
- base-branch: 'main'

# Test changes
tests:
- changed-files:
  - any-glob-to-any-file: '**/*_test.*'
