---
repository:
  name: terragrunt-ref-arch-v3
  description: Modular Infrastructure as Code Reference Architecture with Terragrunt and Terraform
  topics: terragrunt, terraform, infrastructure-as-code, devops, cloud, iac
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: true
  delete_branch_on_merge: true
  has_projects: false
  has_wiki: true

labels:
  - name: infra/terragrunt
    color: '#1D76DB'
    description: Terragrunt configuration and infrastructure changes
  - name: infra/terraform
    color: '#0075CA'
    description: Terraform module modifications
  - name: tool/cli
    color: '#7B42BC'
    description: CLI tool enhancements
  - name: performance
    color: '#FFC300'
    description: Performance optimization for infrastructure code
  - name: config/root
    color: '#5319E7'
    description: Root configuration changes
  - name: config/shared
    color: '#006B75'
    description: Shared configuration modifications
  - name: config/environment
    color: '#207DE5'
    description: Environment-specific configuration updates

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts:
          - "lint"
          - "test"
          - "codecov/project"
      enforce_admins: false
      restrictions:
        apps: []
        teams: []
