---
formatter: markdown table

sections:
  hide:
    - resources # This example creates no resources directly
  show:
    - header
    - requirements
    - providers
    - inputs
    - outputs
    # Show modules called by this example (which is just the read-aws-account module)
    - modules

content: |-
  # Basic Example: Read AWS Account Metadata Module

  ## Overview
  > **Note:** This example demonstrates basic usage of the `read-aws-account` module found in the parent directory (`../`). It simply calls the module to retrieve AWS account metadata like Account ID, Region, Partition, etc.

  ### 🔑 Key Features Demonstrated
  - Calling the `read-aws-account` module.
  - Using fixtures (`fixtures/*.tfvars`) to test enabled/disabled states of the module call.

  ### 📋 Usage Guidelines
  1.  **Configure:** Use the `fixtures/default.tfvars` file (usually empty) or `fixtures/disabled.tfvars` (`is_enabled = false`).
  2.  **Initialize:** Run `terraform init`.
  3.  **Plan:** Run `terraform plan -var-file=fixtures/default.tfvars`.
  4.  **Apply:** Run `terraform apply -var-file=fixtures/default.tfvars`. The outputs will show the retrieved AWS metadata.
  5.  **Makefile:** Alternatively, use the provided `Makefile` targets (`make plan-default`, `make apply-default`).

  {{ .Header }}

  ## Requirements

  {{ .Requirements }}

  ## Providers

  {{ .Providers }}

  ## Example Inputs

  {{ .Inputs }}

  ## Example Outputs

  {{ .Outputs }}

  ## Modules Called

  {{ .Modules }}

output:
  file: README.md
  mode: inject # Use inject to preserve the overview section
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->

settings:
  anchor: true
  color: true
  description: true
  escape: true
  header: true # Show the header section from the template
  html: true
  indent: 2
  required: true
  sensitive: true
  type: true
