---
name: "📕 Documentation Issue"
description: Report an issue in the Terragrunt Reference Architecture documentation
title: "(module name): (short issue description)"
labels: [documentation, needs-triage]
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the documentation issue
      description: A clear and concise description of the documentation problem (missing, incorrect, unclear, etc.).
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Links
      description: Include links to affected documentation page(s) or code references.
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](../../CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
