---
name: Dagger CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  tf_modules_static_check:
    name: Terraform Modules Static Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terraform Modules Static Check
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: "call"
          module: pipeline/infra # Specifies the directory of the Dagger module
          args: job-terraform-modules-static-check # Calls the specific Dagger function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  tg_units_static_check:
    name: Terragrunt Units Static Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terragrunt Units Static Check
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: "call"
          module: pipeline/infra
          args: >-
            job-citg-stack-static-analysis \ --aws-region ${{ env.DEFAULT_REGION }} \ --aws-access-key-id env:AWS_ACCESS_KEY_ID
            \ --aws-secret-access-key env:AWS_SECRET_ACCESS_KEY \ --load-dot-env \ --no-cache \ --environment "global" \ --stack
            "dni"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEFAULT_REGION: "us-east-1"
          TG_NON_INTERACTIVE: "true"
          TG_LOG_LEVEL: "info"
          TG_STACK_REMOTE_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET }}
          TG_STACK_REMOTE_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE }}

  tg_units_plan:
    name: Terragrunt Units Plan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Terragrunt Units Plan
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          verb: "call"
          module: pipeline/infra
          args: >-
            job-tg-exec \ --cmd=plan \ --layer=dni \ --unit=dni_generator \ --aws-access-key-id=env://AWS_ACCESS_KEY_ID \
            --aws-secret-access-key=env://AWS_SECRET_ACCESS_KEY \ --backend-bucket=${{ secrets.TF_STATE_BUCKET }} \ --backend-locktable=${{
            secrets.TF_STATE_LOCK_TABLE }} \ --deployment-region=${{ env.DEFAULT_REGION }} \ --env-vars="TG_NON_INTERACTIVE=$TG_NON_INTERACTIVE,TG_LOG_LEVEL=$TG_LOG_LEVEL"
            \ --environment=global \ --no-cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEFAULT_REGION: "us-east-1"
          TG_NON_INTERACTIVE: "true"
          TG_LOG_LEVEL: "info"
          TG_STACK_REMOTE_STATE_BUCKET_NAME: ${{ secrets.TF_STATE_BUCKET }}
          TG_STACK_REMOTE_STATE_LOCK_TABLE: ${{ secrets.TF_STATE_LOCK_TABLE }}
