---
  name: Release
  on:
    push:
      branches:
      - main
      - '[0-9]+.[0-9]+.x'

  permissions:
    contents: write
    pull-requests: write

  jobs:
    release-please:
      runs-on: ubuntu-latest
      outputs:
        releases_created: ${{ steps.release.outputs.releases_created }}
        tag_name: ${{ steps.release.outputs.tag_name }}
      steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4.1.3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: simple
